test/unit/bdev: fix compilation issue in bdev_io_iobuf_wait_abort
bdev_ut.c: In function 'bdev_io_iobuf_wait_abort':
bdev_ut.c:8055:27: error: passing argument 1 of 'ut_enable_io_type' makes pointer from integer without a cast [-Werror=int-conversion]
 8055 |         ut_enable_io_type(SPDK_BDEV_IO_TYPE_COPY, false);
      |                           ^~~~~~~~~~~~~~~~~~~~~~
      |                           |
      |                           int
bdev_ut.c:411:37: note: expected 'struct spdk_bdev *' but argument is of type 'int'

Issue caused by lack of rebase before merge (confliciting change was
merged before).

Change-Id: I1bc17b3aa48500467e6d5d5343e70626c047be2c
Signed-off-by: Jacek Kalwas <jacek.kalwas@nutanix.com>
Reviewed-on: https://review.spdk.io/c/spdk/spdk/+/27303
Reviewed-by: Tomasz Zawadzki <tomasz@tzawadzki.com>
Bypass-Merge-Requirements: Tomasz Zawadzki <tomasz@tzawadzki.com>