Update patch set 1
Patch Set 1:

> Patch Set 1: Code-Review-1
> 
> Hi Alexey,
> 
> Can you add some more details to the commit message?  x86 was already using -march=native.  I think you mean use -march=native *only* for x86 architecture.  It would be instructive (at least to me) to know why you don't want to use it for other architectures.
> 
> Thanks,
> 
> -Jim

Hi Jim,

Yes, I meant using -march=native only for x86 since this parameter causes compilation error on ARM:
error: unknown value ‘native’ for -march
Maybe it will be more clear if I change the check like this?

 if [[ $arch != aarch64* ]]; then
 	BUILD_CMD=($CC -o /dev/null -x c $CPPFLAGS $CFLAGS $LDFLAGS -march=native)
 else
 	BUILD_CMD=($CC -o /dev/null -x c $CPPFLAGS $CFLAGS $LDFLAGS)
 fi

Patch-set: 1
Reviewer: Gerrit User 1016482 <1016482@d5d70762-12d0-45a1-890d-524b12d3f735>