build: disable maybe-uninitialized warnings with LTO
With LTO enabled, the compiler produces a lot of bogus
maybe-uninitialized warnings, e.g.:

../../../dpdk/build-tmp/../lib/dmadev/rte_dmadev.c: In function ‘dmadev_handle_dev_info’:
../../../dpdk/build-tmp/../lib/dmadev/rte_dmadev.c:933:18: error: ‘dma_info.dev_capa’ may be used uninitialized [-Werror=maybe-uninitialized]
  933 |         dev_capa = dma_info.dev_capa;

Instead of trying to fix all of them, disable these warnings when LTO is
enabled.

Signed-off-by: Konrad Sztyber <konrad.sztyber@intel.com>
Change-Id: I32119e14212a532dba30c40b7303de49249e7512
Reviewed-on: https://review.spdk.io/gerrit/c/spdk/spdk/+/22053
Reviewed-by: Jim Harris <jim.harris@samsung.com>
Reviewed-by: Aleksey Marchuk <alexeymar@nvidia.com>
Tested-by: SPDK CI Jenkins <sys_sgci@intel.com>
Reviewed-by: Michal Berger <michal.berger@intel.com>
Community-CI: Mellanox Build Bot