mk: add include build dependency on lib
The include directory generates spdk_internal/rpc_autogen.h via
genrpc.py. Since commit ca695d71a ("modules: start using auto-gen
RPC code"), multiple module source files include this generated
header. However, the top-level Makefile did not enforce that
include is built before module.

With parallel builds (make -j) this happened to work because
include typically completed before module's RPC sources were
compiled. With sequential make, the DIRS-y ordering caused module
to be built before include, resulting in:
  CC module/bdev/delay/vbdev_delay_rpc.o
  vbdev_delay_rpc.c:12:10: fatal error: spdk_internal/rpc_autogen.h: No such file or directory
     12 | #include "spdk_internal/rpc_autogen.h"
           |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Currently only module is using the rpc_autogen.h, but work is being done to
expand it to lib. Ahead of those changes, add include to lib immidietly.

Change-Id: I4c2c90f8fa4645c5fd223f1b1a26000f9bd12091
Signed-off-by: Tomasz Zawadzki <tomasz.zawadzki@nutanix.com>
Reported-by: AdarshPradhanJMT <AdarshPradhan.Jmt@dell.com>
Reviewed-on: https://review.spdk.io/c/spdk/spdk/+/27955
Reviewed-by: Aleksey Marchuk <alexeymar@nvidia.com>
Tested-by: SPDK Automated Test System <spdkbot@gmail.com>
Community-CI: Mellanox Build Bot
Reviewed-by: Adarsh Pradhan JMT <AdarshPradhan.Jmt@dell.com>
Reviewed-by: Jim Harris <jim.harris@nvidia.com>
Reviewed-by: Boris Glimcher <Boris.Glimcher@emc.com>