lib/ublk: Remove unused member of ublksrv_ctrl_cmd struct
This is a minimal-effort version of the following patch:
https://review.spdk.io/gerrit/c/spdk/spdk/+/18590

The commit message of the above patch does not mention it
but this change is needed to make sure v23.01.x's ublk
support can be properly built against newer kernels where
due to:

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=4093cb5a06343

inline data's size change, building SPDK with ublk support
enabled can lead to:

ublk.c:296:3: error: array index 1 is past the end of the array (that
has type '__u64[1]' (aka 'unsigned long long[1]')) [-Werror,-Warray-bounds]

Change-Id: Ib53c0dc038aff91060809110fb9f2989eb6d4cc9
Signed-off-by: Michal Berger <michal.berger@intel.com>
Reviewed-on: https://review.spdk.io/gerrit/c/spdk/spdk/+/20906
Tested-by: SPDK CI Jenkins <sys_sgci@intel.com>
Reviewed-by: Konrad Sztyber <konrad.sztyber@intel.com>
Reviewed-by: Changpeng Liu <changpeng.liu@intel.com>