Update patch set 10
Patch Set 10: Code-Review-1

Unable to link using the implicit linker script (libspdk.so).  After building the tree, I attempted to make the nvmf_tgt relying on:  libspdk.so + libspdk_env_dpdk.so + dpdk libs + system libs, but I get lots of:

$DESTDIR/usr/local/lib/libspdk_vhost.so: undefined reference to 'rte_XXXX'.

I thought I recalled a previous patch set with spdk_vhost removed from the monolithic libspdk.so, right?

Patch-set: 10
Reviewer: Lance Hartmann <1011995@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Code-Review=-1