Update patch set 19
Patch Set 19:

(1 comment)

Hi Anil,

I confirmed the following patterns:
1.  the option that had caused CI failures.
2.  ./configure --with-fc

I saw the following error when I added --with-fc to the option #1, but we will be able to leave the pattern for now.

  CC test/unit/lib/nvmf/fc.c/fc_ut.o
fc_ut.c:87:2: error: unknown field ‘qpair_is_idle’ specified in initializer
  .qpair_is_idle = NULL,
  ^
fc_ut.c:88:2: error: initialized field overwritten [-Werror=override-init]
  .qpair_get_peer_trid = NULL,
  ^
fc_ut.c:88:2: error: (near initialization for ‘spdk_nvmf_transport_rdma.qpair_get_peer_trid’) [-Werror=override-init]
cc1: all warnings being treated as errors
make[5]: *** [fc_ut.o] Error 1
make[4]: *** [fc.c] Error 2
make[3]: *** [nvmf] Error 2
make[2]: *** [lib] Error 2
make[1]: *** [unit] Error 2

Patch-set: 19
Reviewer: Gerrit User 1012251 <1012251@d5d70762-12d0-45a1-890d-524b12d3f735>