scripts/nvmf performance: fix config param and connection error
Fixed the following:
1) Missing python paramiko module in package dependecies.
2) Paramiko connection error: TypeError: missing_host_key() missing 1 required positional argument: 'key'
The set_missing_host_key_policy call should take a class instance AutoAddPolicy(), instead of the class name.
3) JSON config file defines "rdma_ips" instead of "nic_ips"
4) Added result file location in the documentation
5) Added env variable for PYTHONPATH to documentation
6) config.json changed default rw to randrw instead of read

Signed-off-by: John Kariuki <John.K.Kariuki@intel.com>
Reviewed-on: https://review.gerrithub.io/c/spdk/spdk/+/455285 (master)

(cherry picked from commit d601374387bc25571e0e2df5e4e138b2f75d9d34)
Change-Id: I96624e2912131f62254c684a6c03a53a7f806cde
Signed-off-by: Tomasz Zawadzki <tomasz.zawadzki@intel.com>