autopackage: disable unit tests
It doesn't make sense to include them as part of a release build and
they introduce bogus compiler warnings with LTO enabled:

nvme_pcie_common_ut.c: In function ‘test_nvme_pcie_poll_group_get_stats’:
nvme_pcie_common_ut.c:575:9: error: ‘__builtin_memcmp_eq’ specified bound 72 exceeds source size 0 [-Werror=stringop-overread]
  575 |         CU_ASSERT(memcmp(&tgroup_stat->pcie, &pgroup->stats, sizeof(struct spdk_nvme_pcie_stat)) == 0);
      |         ^

Fixes #3274

Signed-off-by: Konrad Sztyber <konrad.sztyber@intel.com>
Change-Id: I021367f021647a018aa734f6d0bcd9721824a4a7
Reviewed-on: https://review.spdk.io/gerrit/c/spdk/spdk/+/22059
Reviewed-by: Aleksey Marchuk <alexeymar@nvidia.com>
Tested-by: SPDK CI Jenkins <sys_sgci@intel.com>
Reviewed-by: Jim Harris <jim.harris@samsung.com>
Reviewed-by: Michal Berger <michal.berger@intel.com>