test/nvme: add missing stubs in unit tests for nvme_auth
Recent patch introduced new unit tests for nvme_auth but missed stub
declarations. When SPDK_CONFIG_HAVE_EVP_MAC is set this leads to series
of 'undefined reference to' linker errors in nvme_auth_ut.

Fixes:
41e4230c4 ("test/nvme: add unit tests for nvme_auth")

Change-Id: I4df9195522a38e87bfc502787c6d15551551793d
Signed-off-by: Krzysztof Goreczny <krzysztof.goreczny@dell.com>
Reviewed-on: https://review.spdk.io/c/spdk/spdk/+/28254
Community-CI: Mellanox Build Bot
Reviewed-by: Konrad Sztyber <ksztyber@nvidia.com>
Reviewed-by: Boris Glimcher <Boris.Glimcher@emc.com>
Reviewed-by: Jim Harris <jim.harris@nvidia.com>
Tested-by: SPDK Automated Test System <spdkbot@gmail.com>