scripts/pkgdep: install missing pip-tools dependency
pip-tools 7.6.0 imports typing_extensions.Self on Python older than
3.11, but does not declare typing-extensions as a dependency, so
pip-compile fails right after the virtualenv is bootstrapped on
Debian 11 and Ubuntu 22.04:

File ".../piptools/writer.py", line 33, in <module>
from typing_extensions import Self as _t_Self
ModuleNotFoundError: No module named 'typing_extensions'

Install it with the same requirement upstream added in pip-tools commit
a2035a1335 ("Add missing dependency on typing-extensions") for
jazzband/pip-tools#2424. That fix is not part of any release yet. Python
3.11 and newer keep using typing.Self from the standard library, so the
marker skips the install there.

Change-Id: Iebe9138194723998af0e3344bb5112b53c467d4a
Assisted-by: Cursor
Signed-off-by: Tomasz Zawadzki <tomasz.zawadzki@nutanix.com>
Reviewed-on: https://review.spdk.io/c/spdk/spdk/+/29034
Tested-by: SPDK Automated Test System <spdkbot@gmail.com>
Reviewed-by: Jim Harris <jim.harris@nvidia.com>
Reviewed-by: Karol Latecki <karol.latecki@nutanix.com>
Reviewed-by: Konrad Sztyber <ksztyber@nvidia.com>
Reviewed-by: Boris Glimcher <Boris.Glimcher@emc.com>
Reviewed-by: Michal Berger <michal.berger@nutanix.com>