Update patch set 11
Patch Set 11:

(1 comment)

> Patch Set 11:
> 
> (2 comments)

Hi Konrad,

I tried to update my patch that I place my patch on your patch, but I failed.
Please advice me. Thank you!

-----
Checkout Konrad’s patch
 
$ git checkout -b konrad
$ git checkout master
 
Checkout Claire’s patch
 
$ git checkout -b claire
$ git rebase -i konrad
$ git rebase -i master

---
$ git log
commit d89d796d5125b81bf73f8f6ff65ad3dfda565bd9 (HEAD -> rsopt3)
Author: Claire J. In <claire.in@circuitblvd.com>
Date:   Wed Apr 10 10:37:52 2019 -0700

    lib/ftl: consider 3D TLC NAND read unit size

    For the latest TLC NAND, one write buffer unit (rwb batch)
    ...
    Change-Id: I371e72067b278ef43c3ac87a3d9ce9010d3fcb15
    Signed-off-by: Claire J. In <claire.in@circuitblvd.com>

commit f529e926add5f38ab3f9760458bc73624e353566
Author: Konrad Sztyber <konrad.sztyber@intel.com>
Date:   Fri Apr 19 10:40:12 2019 +0200

    lib/ftl: check config after geometry is retrieved

    Moved device configuration checks inside ftl_check_init_opts to allow
    for validation against the geometry of the drive.

    Change-Id: I8e813d30ef5feba641517872ce068824442cfdbc
    Signed-off-by: Konrad Sztyber <konrad.sztyber@intel.com>

commit cbf74b20b37d0b2e76a9e95415f3478deac81208 (origin/master, origin/HEAD, master)
Author: Seth Howell <seth.howell@intel.com>


----

# git push review                           Enumerating objects: 41, done.
Counting objects: 100% (41/41), done.
Delta compression using up to 4 threads
Compressing objects: 100% (20/20), done.
Writing objects: 100% (25/25), 5.89 KiB | 5.89 MiB/s, done.
Total 25 (delta 20), reused 5 (delta 5)
remote: Resolving deltas: 100% (20/20)
remote: Counting objects: 21983, done
remote: Processing changes: refs: 1, done
To https://review.gerrithub.io/spdk/spdk
 ! [remote rejected]     HEAD -> refs/for/master (cannot add patch set to 451516.)
error: failed to push some refs to 'https://review.gerrithub.io/spdk/spdk'

Patch-set: 11
Reviewer: Gerrit User 1016114 <1016114@d5d70762-12d0-45a1-890d-524b12d3f735>