libvfio-user: update submodule to respect newer kernel vfio.h definitions
This patch moves the libvfio-user submodule forward by single commit:
(b52bff7)libvfio-user.h: sync VFIO_DEVICE_STATE_XXXX definitions with upstream

The vfio.h header definitions were updated and without the patch above,
following errors can be observed on newer systems (Fedora 35+):
In file included from ../../../libvfio-user/lib/pci_caps.h:36,
                 from ../../../libvfio-user/lib/pci.c:40:
../../../libvfio-user/include/libvfio-user.h:680: error: "VFIO_DEVICE_STATE_MASK" redefined [-Werror]
  680 | #define VFIO_DEVICE_STATE_MASK ((1 << 3) - 1)
      |
In file included from ../../../libvfio-user/include/vfio-user.h:46,
                 from ../../../libvfio-user/include/libvfio-user.h:57,
                 from ../../../libvfio-user/lib/pci_caps.h:36,
                 from ../../../libvfio-user/lib/pci.c:40:
/usr/include/linux/vfio.h:416: note: this is the location of the previous definition

Signed-off-by: Tomasz Zawadzki <tomasz.zawadzki@intel.com>
Change-Id: I52dcfd5caa51a4ef7710e36362ecc2b59d09f6cf
Reviewed-on: https://review.spdk.io/gerrit/c/spdk/spdk/+/13414 (master)
(cherry picked from commit a2e2378fb4f0a60b87303392b512a957e82e4aff)
Reviewed-on: https://review.spdk.io/gerrit/c/spdk/spdk/+/13506
Reviewed-by: Kamil Godzwon <kamilx.godzwon@intel.com>
Reviewed-by: Ben Walker <benjamin.walker@intel.com>
Reviewed-by: Jim Harris <james.r.harris@intel.com>
Reviewed-by: Changpeng Liu <changpeng.liu@intel.com>
Tested-by: SPDK CI Jenkins <sys_sgci@intel.com>