Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> it solved some of this issues indeed. 
> but also report :
> 
> iscsi_ut.c:667:2: error: expression is not assignable

Ah, I assumed the element param must be an lvalue, which is not true. Thanks, fixed now.

Patch-set: 1