Update patch set 3
Patch Set 3:

So the suggestion flag flagged a potential issue here:

rdma.c:1240:3: error: assuming signed overflow does not occur when reducing constant in comparison [-Werror=strict-overflow]
   max_queue_depth = spdk_min(max_queue_depth, private_data->hsqsize + 1);

Do we think its worth addressing this (and whatever else it may find) or are we just making busy work for ourselves?

Patch-set: 3
Reviewer: Gerrit User 1011289 <1011289@d5d70762-12d0-45a1-890d-524b12d3f735>