pkgdep/git: Bump nvme-cli to v2.0 release
Older compilers (e.g. 7.5 on ubuntu1804) are having issues under
v1.16 due to:

plugins/intel/intel-nvme.c:666:47: error: initializer element is not constant
static const int LATENCY_STATS_V4_BASE_VAL = (
Makefile:108: recipe for target 'plugins/intel/intel-nvme.o' failed

This was fixed by the following commit which is present in the v2.0
release:

https://github.com/linux-nvme/nvme-cli/commit/e7309044f3ed48b0b6138dfc22a72d8fc1108580

Signed-off-by: Michal Berger <michal.berger@intel.com>
Change-Id: I7ebcf1b1fdb44500a21bcf3feceb07a722e8fc30
Reviewed-on: https://review.spdk.io/gerrit/c/spdk/spdk/+/13775
Tested-by: SPDK CI Jenkins <sys_sgci@intel.com>
Reviewed-by: Jim Harris <james.r.harris@intel.com>
Reviewed-by: Dong Yi <dongx.yi@intel.com>
Reviewed-by: Tomasz Zawadzki <tomasz.zawadzki@intel.com>